from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path
from typing import cast


TYPE_REPLACEMENTS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^datetime$", re.I), "timestamp without time zone"),
    (re.compile(r"^timestamp$", re.I), "timestamp without time zone"),
    (re.compile(r"^date$", re.I), "date"),
    (re.compile(r"^time$", re.I), "time without time zone"),
    (re.compile(r"^bigint(?:\(\d+\))?$", re.I), "bigint"),
    (re.compile(r"^int(?:eger)?(?:\(\d+\))?$", re.I), "integer"),
    (re.compile(r"^mediumint(?:\(\d+\))?$", re.I), "integer"),
    (re.compile(r"^smallint(?:\(\d+\))?$", re.I), "smallint"),
    (re.compile(r"^tinyint(?:\(\d+\))?$", re.I), "smallint"),
    (re.compile(r"^double(?:\s+precision)?$", re.I), "double precision"),
    (re.compile(r"^float$", re.I), "double precision"),
    (re.compile(r"^longtext$", re.I), "text"),
    (re.compile(r"^mediumtext$", re.I), "text"),
    (re.compile(r"^text$", re.I), "text"),
    (re.compile(r"^longblob$", re.I), "bytea"),
    (re.compile(r"^blob$", re.I), "bytea"),
]


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def sql_literal(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def strip_trailing_comma(text: str) -> tuple[str, bool]:
    stripped = text.rstrip()
    has_comma = stripped.endswith(",")
    return (stripped[:-1].rstrip() if has_comma else stripped, has_comma)


def replace_backticks(text: str) -> str:
    return re.sub(r"`([^`]+)`", lambda m: quote_ident(m.group(1)), text)


def normalize_index_name(table: str, raw_name: str) -> str:
    base = re.sub(r"[^a-zA-Z0-9_]+", "_", f"idx_{table}_{raw_name}").lower().strip("_")
    if len(base) <= 63:
        return base
    suffix = hashlib.sha1(base.encode("utf-8")).hexdigest()[:10]
    return f"{base[:52]}_{suffix}"


def split_type_and_attrs(rest: str) -> tuple[str, str]:
    depth = 0
    for idx, ch in enumerate(rest):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch.isspace() and depth == 0:
            return rest[:idx], rest[idx:].strip()
    return rest, ""


def map_type(mysql_type: str, attrs: str) -> tuple[str, str]:
    t = re.sub(r"\s+unsigned\b", "", mysql_type, flags=re.I).strip()
    mapped = t
    for pattern, replacement in TYPE_REPLACEMENTS:
        if pattern.match(t):
            mapped = replacement
            break
    return mapped, re.sub(r"\bunsigned\b", "", attrs, flags=re.I).strip()


def normalize_default(attrs: str) -> str:
    attrs = re.sub(r"\bAUTO_INCREMENT\b", "", attrs, flags=re.I)
    attrs = re.sub(r"\bON UPDATE CURRENT_TIMESTAMP\b", "", attrs, flags=re.I)
    attrs = re.sub(
        r"DEFAULT\s+'0000-00-00 00:00:00'",
        "DEFAULT '1970-01-01 00:00:00'",
        attrs,
        flags=re.I,
    )
    attrs = re.sub(r"DEFAULT\s+'0000-00-00'", "DEFAULT '1970-01-01'", attrs, flags=re.I)
    attrs = re.sub(
        r"\bCURRENT_TIMESTAMP\(\d+\)", "CURRENT_TIMESTAMP", attrs, flags=re.I
    )
    attrs = re.sub(r"\s+", " ", attrs).strip()
    return attrs


def parse_column(line: str) -> tuple[str, str, str | None, bool]:
    body, has_comma = strip_trailing_comma(line)
    comment: str | None = None
    comment_match = re.search(
        r"\s+COMMENT\s+'((?:''|\\'|[^'])*)'\s*$", body, flags=re.I
    )
    if comment_match:
        comment = comment_match.group(1).replace("''", "'").replace("\\'", "'")
        body = body[: comment_match.start()].rstrip()

    col_match = re.match(r"`([^`]+)`\s+(.+)$", body)
    if not col_match:
        raise ValueError(f"Cannot parse column line: {line}")

    col_name = col_match.group(1)
    rest = col_match.group(2).strip()
    mysql_type, attrs = split_type_and_attrs(rest)
    pg_type, attrs = map_type(mysql_type, attrs)
    attrs = normalize_default(attrs)
    is_identity = bool(re.search(r"\bAUTO_INCREMENT\b", line, flags=re.I))

    parts = [quote_ident(col_name), pg_type]
    if is_identity:
        parts.append("GENERATED BY DEFAULT AS IDENTITY")
    if attrs:
        parts.append(attrs)

    return col_name, " ".join(parts), comment, has_comma


def convert_key_line(table_name: str, line: str) -> str | None:
    body, _ = strip_trailing_comma(line)
    body = re.sub(r"\s+USING\s+BTREE", "", body, flags=re.I)

    pk_match = re.match(r"PRIMARY KEY\s*\((.+)\)$", body, flags=re.I)
    if pk_match:
        return f"PRIMARY KEY ({replace_backticks(pk_match.group(1))})"

    uq_match = re.match(r"UNIQUE KEY\s+`([^`]+)`\s*\((.+)\)$", body, flags=re.I)
    if uq_match:
        idx_name = normalize_index_name(table_name, uq_match.group(1))
        cols = replace_backticks(uq_match.group(2))
        return f"CREATE UNIQUE INDEX {quote_ident(idx_name)} ON {quote_ident(table_name)} ({cols});"

    key_match = re.match(r"(?:KEY|INDEX)\s+`([^`]+)`\s*\((.+)\)$", body, flags=re.I)
    if key_match:
        idx_name = normalize_index_name(table_name, key_match.group(1))
        cols = replace_backticks(key_match.group(2))
        return f"CREATE INDEX {quote_ident(idx_name)} ON {quote_ident(table_name)} ({cols});"

    constraint_match = re.match(r"CONSTRAINT\s+`([^`]+)`\s+(.+)$", body, flags=re.I)
    if constraint_match:
        constraint_name = quote_ident(constraint_match.group(1))
        remainder = replace_backticks(constraint_match.group(2))
        return f"CONSTRAINT {constraint_name} {remainder}"

    return replace_backticks(body)


def build_seed_sql() -> str:
    return """BEGIN;
SET client_min_messages TO WARNING;
SET session_replication_role = replica;

DO $$
DECLARE
    t record;
    c record;
    has_rows boolean;
    cols text;
    vals text;
    stmt text;
BEGIN
    FOR t IN
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
        ORDER BY table_name
    LOOP
        EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I.%I)', 'public', t.table_name) INTO has_rows;
        IF has_rows THEN
            CONTINUE;
        END IF;

        cols := '';
        vals := '';

        FOR c IN
            SELECT
                column_name,
                data_type,
                udt_name,
                ordinal_position
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = t.table_name
              AND is_nullable = 'NO'
              AND column_default IS NULL
              AND coalesce(is_identity, 'NO') = 'NO'
              AND coalesce(is_generated, 'NEVER') = 'NEVER'
            ORDER BY ordinal_position
        LOOP
            cols := cols || CASE WHEN cols = '' THEN '' ELSE ', ' END || format('%I', c.column_name);
            vals := vals || CASE WHEN vals = '' THEN '' ELSE ', ' END ||
                CASE
                    WHEN c.data_type IN ('character varying', 'character', 'text') THEN quote_literal(left(t.table_name || '_' || c.column_name || '_test', 120))
                    WHEN c.data_type IN ('timestamp without time zone', 'timestamp with time zone') THEN quote_literal('2024-01-01 00:00:00')
                    WHEN c.data_type = 'date' THEN quote_literal('2024-01-01')
                    WHEN c.data_type = 'time without time zone' THEN quote_literal('00:00:00')
                    WHEN c.data_type = 'boolean' THEN 'false'
                    WHEN c.data_type IN ('smallint', 'integer', 'bigint', 'numeric', 'real', 'double precision') THEN '1'
                    WHEN c.data_type = 'uuid' THEN quote_literal('00000000-0000-0000-0000-000000000001')
                    WHEN c.data_type IN ('json', 'jsonb') THEN quote_literal('{}')
                    WHEN c.udt_name = 'bytea' THEN 'decode('''', ''hex'')'
                    ELSE quote_literal('sample')
                END;
        END LOOP;

        BEGIN
            IF cols = '' THEN
                stmt := format('INSERT INTO %I.%I DEFAULT VALUES', 'public', t.table_name);
            ELSE
                stmt := format('INSERT INTO %I.%I (%s) VALUES (%s)', 'public', t.table_name, cols, vals);
            END IF;
            EXECUTE stmt;
        EXCEPTION
            WHEN OTHERS THEN
                RAISE NOTICE 'Skip table % due to: %', t.table_name, SQLERRM;
        END;
    END LOOP;
END $$;

SET session_replication_role = DEFAULT;
COMMIT;
"""


def convert_mysql_dump(input_path: Path, output_path: Path, seed_output: Path) -> None:
    text = input_path.read_text(encoding="utf-8", errors="ignore")
    lines = text.splitlines()
    out: list[str] = [
        "BEGIN;",
        "SET client_min_messages TO WARNING;",
        "SET search_path TO public;",
        "",
    ]

    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if (
            not line
            or line.startswith("/*")
            or line.startswith("--")
            or line == "SET FOREIGN_KEY_CHECKS=0;"
        ):
            i += 1
            continue

        if line.startswith("DROP TABLE IF EXISTS"):
            match = re.match(r"DROP TABLE IF EXISTS `([^`]+)`;", line)
            if match:
                out.append(
                    f"DROP TABLE IF EXISTS {quote_ident(match.group(1))} CASCADE;"
                )
                out.append("")
            i += 1
            continue

        if line.startswith("CREATE TABLE"):
            table_match = re.match(r"CREATE TABLE `([^`]+)` \($", line)
            if not table_match:
                raise ValueError(f"Cannot parse CREATE TABLE line: {lines[i]}")
            table_name = table_match.group(1)
            i += 1
            raw_block: list[str] = []
            while i < len(lines):
                raw_block.append(lines[i])
                if lines[i].strip().endswith(";"):
                    break
                i += 1
            if not raw_block:
                raise ValueError(f"CREATE TABLE block for {table_name} is incomplete")

            closing = raw_block[-1].strip()
            body_lines = raw_block[:-1]
            table_comment_match = re.search(r"COMMENT='((?:''|\\'|[^'])*)'", closing)
            table_comment = (
                table_comment_match.group(1).replace("''", "'").replace("\\'", "'")
                if table_comment_match
                else None
            )

            columns: list[str] = []
            extra_defs: list[str] = []
            post_statements: list[str] = []
            column_comments: list[tuple[str, str]] = []

            for raw_line in body_lines:
                stripped = raw_line.strip()
                if not stripped:
                    continue
                if stripped.startswith("`"):
                    col_name, col_def, comment, _ = parse_column(stripped)
                    columns.append(f"    {col_def}")
                    if comment:
                        column_comments.append((col_name, comment))
                    continue

                converted = convert_key_line(table_name, stripped)
                if converted is None:
                    continue
                if converted.startswith("CREATE "):
                    post_statements.append(converted)
                else:
                    extra_defs.append(f"    {converted}")

            create_lines = columns + extra_defs
            out.append(f"CREATE TABLE {quote_ident(table_name)} (")
            out.append(",\n".join(create_lines))
            out.append(");")

            if table_comment:
                out.append(
                    f"COMMENT ON TABLE {quote_ident(table_name)} IS {sql_literal(table_comment)};"
                )
            for col_name, comment in column_comments:
                out.append(
                    f"COMMENT ON COLUMN {quote_ident(table_name)}.{quote_ident(col_name)} IS {sql_literal(comment)};"
                )
            out.extend(post_statements)
            out.append("")
            i += 1
            continue

        if line.startswith("INSERT INTO"):
            statement_lines = [lines[i]]
            while not statement_lines[-1].strip().endswith(";"):
                i += 1
                statement_lines.append(lines[i])
            i += 1
            continue

        i += 1

    out.append("COMMIT;")
    _ = output_path.write_text("\n".join(out) + "\n", encoding="utf-8")
    _ = seed_output.write_text(build_seed_sql(), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert a MySQL dump to PostgreSQL DDL and seed SQL"
    )
    _ = parser.add_argument("input", type=Path)
    _ = parser.add_argument("output", type=Path)
    _ = parser.add_argument(
        "--seed-output", dest="seed_output", type=Path, required=True
    )
    args = parser.parse_args()

    input_path = cast(Path, args.input)
    output_path = cast(Path, args.output)
    seed_output = cast(Path, args.seed_output)
    convert_mysql_dump(input_path, output_path, seed_output)


if __name__ == "__main__":
    main()
