services:
  gosqlbot-app:
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.4-alpine
    container_name: sqlbot-redis
    restart: always
    networks:
      - sqlbot-network
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

networks:
  sqlbot-network:
